### PR TITLE
Gitbook docs changes and automatic pr generation on docs repo

### PR DESCRIPTION
**Pull request by Neelterminusdb**
[CI: added steps for generating markdown and creating new pr](https://github.com/terminusdb/terminusdb-client-python/commit/9025d39a853a526052beb7b09a9484fe6d2b8505)

[docs: added script to convert spnix docs to gitbook markdown](https://github.com/terminusdb/terminusdb-client-python/commit/71862fef33d9cf118eac58a9c1d35c99a317f28a)

### CODE REVIEW

**Comment by Cheukting** [comment]
Just a minor thing, in Python we use snake_case for variable names instead of CamelCase

**Comment by spl** [comment]
After this is merged, close https://github.com/terminusdb/terminusdb-docs/issues/104.

**Comment by Cheukting** [comment]
@Neelterminusdb do you want me to merge it?

**Comment by Cheukting** [comment]
I notice the CI in this PR is taking very long. Since @Neelterminusdb 's work is only on the CI and doc side. @rrooij do you mind having a look at the CI to see what breaks the previous setup?

**Comment by Neelterminusdb** [comment]
It seems while running the test step in python.yml action it is taking a lot more time then it needs to and then failing

**Comment by Neelterminusdb** [comment]
Screenshot 2022-05-17 at 11 44 56 PM
from the actions log

**Comment by Cheukting** [comment]
I was suspecting the code coverage is broken by this but cannot pin point
why from the error log of the CI test. Do you mind running the test locally
and see?

**Comment by Cheukting** [comment]
And from the pytest output the test that failed are those using the token
for TerminusX. That’s why I think there’s something wrong with the CI

**Comment by Cheukting** [comment]
I think it is normal for code coverage to fail if the tests failed and don't know why it is only those with TerminusX that failed

**Comment by Cheukting** [comment]
@Neelterminusdb I have a crazy idea, maybe try removing the `passenv = TERMINUSX_TOKEN` in tox.ini to see if the test passes? We need it but by try without it we can try pin down where the problem is

**Comment by Neelterminusdb** [comment]
When i remove the `passenv = TERMINUSX_TOKEN` from the tox.ini file and run the command tox -e test it gives me an error which says :

```
ERROR: could not install deps [--no-deps, -rrequirements.txt]; v = InvocationError('/Users/neel/Desktop/TerminusDB/terminusdb-client-python/.tox/test/bin/python -m pip install --no-deps -rrequirements.txt', 1)
________________________________________________________________________________________ summary _________________________________________________________________________________________
ERROR:   test: could not install deps [--no-deps, -rrequirements.txt]; v = InvocationError('/Users/neel/Desktop/TerminusDB/terminusdb-client-python/.tox/test/bin/python -m pip install --no-deps -rrequirements.txt', 1)
```
And if i run tests as suggested in readme file by running this command `poetry run pytest terminusdb_client/tests`

It runs some tests sucessfully but gives and error while running tests which are related to terminusX

**Comment by Cheukting** [comment]
This error means that you have not done ‘tox -e deps’ try doing ‘tox’
instead of just tests

**Comment by Cheukting** [comment]
Or you can just remove that line and push to this PR, we can reset it later

**Comment by Neelterminusdb** [comment]
I did ran the tox -e deps before running the test command, i will change the line in the pr for now

**Comment by Cheukting** [comment]
@Neelterminusdb so test passes (ignore code coverage for now) and yes the problem is TerminusX, but I don't know why your PR will make them fail in a funny way

**Comment by Cheukting** [comment]
TerminusX fails quite often when I run the tests and I have to rerun the jobs then they are fine. I wonder if that is normal?

**Comment by rrooij** [comment]
Further work here: https://github.com/terminusdb/terminusdb-client-python/pull/323

**Pull request closed without merging**
