### PR TITLE
rename cli

### LINKED ISSUE #310: rename cli tool to `tdbpy`
- [ ] rename cli tool to `tdbpy`
- [ ] update docs

### PR DESCRIPTION
**Pull request by Cheukting**
rename cli to `tdbpy`

closes #310

### CODE REVIEW

**Comment by spl** [comment]
The original issue was <https://github.com/terminusdb/terminusdb-client-python/issues/242>.

**Comment by spl** [comment]
@Neelterminusdb will review this.

**Comment by Neelterminusdb** [comment]
Looks good to me @spl I tried using the tdbpy locally but was unable to do it as i didnt know how one can debug python client locally using pip.

**Comment by Neelterminusdb** [comment]
Yes i have a old version of python client thats why i was not able to use `tdbpy`. Great that you have checked it and is working

**Pull request merged**
